# ---****Ejercicio 4  VB  -  POO****---
import ClaseVentana as Class

if __name__=="__main__":
    print('==== Ventana Inicio ====')
    ventanaInicio= Class.Ventana('Inicio')
    ventanaInicio.mostrar()
    print('Ventana: {} Alto: {} Ancho: {}'.format(ventanaInicio.getTitulo(),ventanaInicio.alto(),ventanaInicio.ancho()))
    print('==== Ventana Cargar ====')
    ventanaCargar= Class.Ventana('Cargar',10,20)
    ventanaCargar.mostrar()
    print('*** Mueve a la derecha ***')
    ventanaCargar.moverDerecha(10)
    ventanaCargar.mostrar()
    print('*** Mueve a la izquierda ***')
    ventanaCargar.moverIzquierda(10)
    ventanaCargar.mostrar()
    print('*** Bajar ***')
    ventanaCargar.bajar(10)
    ventanaCargar.mostrar()
    print('==== Ventana Borrar ====')
    ventanaBorrar = Class.Ventana('Borrar', 10,20,100,200)
    ventanaBorrar.mostrar()
    print('*** Subir ***')
    ventanaBorrar.subir(99)   
    ventanaBorrar.mostrar()
    print('*** Subir ***')
    ventanaBorrar.subir(7)
    ventanaBorrar.mostrar()
    print('*** Bajar ***')
    ventanaBorrar.bajar(3)
    ventanaBorrar.mostrar()